// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrbisEvents.Data;

namespace OrbisEvents.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190918194643_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("OrbisEvents.Data.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CreatedById");

                    b.Property<string>("Description");

                    b.Property<DateTime?>("EndTime");

                    b.Property<int?>("MaxRegistrations");

                    b.Property<DateTime?>("StartTime");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("events");
                });

            modelBuilder.Entity("OrbisEvents.Data.Models.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DateRegistered");

                    b.Property<int?>("EventId");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("registrations");
                });

            modelBuilder.Entity("OrbisEvents.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("MiddleName");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("OrbisEvents.Data.Models.Event", b =>
                {
                    b.HasOne("OrbisEvents.Data.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");
                });

            modelBuilder.Entity("OrbisEvents.Data.Models.Registration", b =>
                {
                    b.HasOne("OrbisEvents.Data.Models.Event", "Event")
                        .WithMany("Registrations")
                        .HasForeignKey("EventId");

                    b.HasOne("OrbisEvents.Data.Models.User", "User")
                        .WithMany("Registrations")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
